[workspace]
name = "VirtualShip"
preview = ["pixi-build"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
exclude-newer = "5d" # security pre-caution against compromised packages
requires-pixi = ">=0.72.0"

[package]
name = "virtualship"
version = "dynamic" # dynamic versioning needs better support in pixi https://github.com/prefix-dev/pixi/issues/2923#issuecomment-2598460666 . Putting `version = "dynamic"` here for now until pixi recommends something else.

[package.build]
backend = { name = "pixi-build-python", version = "0.*" }

[package.host-dependencies]
setuptools = "*"
setuptools_scm = "*"

[package.run-dependencies] # Keep in sync with `pyproject.toml` dependencies
python = ">=3.11"
click = "*"
pyproj = ">=3,<4"
sortedcontainers = "==2.4.0"
opensimplex = "==0.4.5"
numpy = ">=2.1.0"
pydantic = ">=2,<3"
pyyaml = "*"
copernicusmarine = ">=2.2.2"
yaspin = "*"
textual = "*"

[dependencies]
virtualship = { path = "." }
# Pre-install as conda packages to avoid PyPI source builds
netcdf4 = "*"
numpy = ">=2.1.0"
dask = "*"
pandas = "*"
pyarrow = "*"
ipdb = ">=0.13.13,<0.14"
cmocean = ">=4.0.3,<5"
numba = ">=0.59.0"

[pypi-dependencies]
parcels = { git = "https://github.com/Parcels-code/Parcels", branch = "main" }

[feature.py311.dependencies]
python = "3.11.*"
zarr = ">=3.0.0"

[feature.py314.dependencies]
python = "3.14.*"
zarr = ">=3.0.0"

[feature.test.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-asyncio = "*"
seabird = "*"
openpyxl = "*"

[feature.test.tasks]
tests = "pytest"

[feature.notebooks.dependencies]
nbval = "*"
ipykernel = "*"

[feature.notebooks.tasks]
tests-notebooks = "pytest --nbval-lax docs/"

[feature.analysis.dependencies]
jupyterlab = ">=4,<5"
ipykernel = ">=7,<8"
plotly = ">=6,<7"
nbformat = "*"
ipywidgets = "*"

[feature.analysis.tasks]
lab = "jupyter lab"

[feature.docs.dependencies]
sphinx = ">=7.0"
myst-parser = ">=0.13"
nbsphinx = "*"
ipykernel = "*"
pandoc = "*"
sphinx-copybutton = "*"
pydata-sphinx-theme = "*"
sphinx-autobuild = "*"

[feature.docs.tasks]
docs = "sphinx-build docs docs/_build"
docs-watch = "sphinx-autobuild docs docs/_build"

[feature.pre-commit.dependencies]
pre_commit = "*"

[feature.pre-commit.tasks]
lint = "pre-commit run --all-files"

[feature.typing.dependencies]
mypy = "*"
lxml = "*"
pandas-stubs="*"
types-PyYAML="*"
scipy-stubs="*"
types-openpyxl = "*"
types-psutil = "*"
types-python-dateutil = "*"

[feature.typing.pypi-dependencies]
types-xlrd = "*"

[feature.typing.tasks]
typing = "mypy src/virtualship --install-types"

[environments]
default = { features = ["py314", "test", "notebooks", "typing", "pre-commit", "analysis"], solve-group = "main" }
test-latest = { features = ["py314", "test"], solve-group = "test-py314" }
test-py311 = { features = ["py311", "test"], solve-group = "test-py311" }
test-py314 = { features = ["py314", "test"], solve-group = "test-py314" }
test-notebooks = { features = ["py314", "test", "notebooks"], solve-group = "test-py314" }
analysis = { features = ["py314", "analysis"], solve-group = "analysis" }
docs = { features = ["py314", "docs"], solve-group = "docs" }
typing = { features = ["py314", "typing"], solve-group = "main" }
pre-commit = { features = ["pre-commit"], no-default-feature = true }
